function specs=specOpenV2(filename)
    file_text = fileread(filename);
    file_lines = splitlines(file_text);
    
    structure = struct(...
        "task_type",            file_lines(3), ...
        "wav_filename",         file_lines(5), ...
        "wav_fs",               file_lines(7), ...
        "signal_type",          file_lines(10), ...
        "fs",                   file_lines(12), ...
        "signal_duration_s",    file_lines(14), ...
        "periodicity_s",        file_lines(16), ...
        "frequencies",          file_lines(18), ...
        "spectral_resolution",  file_lines(21), ...
        "window_type",          file_lines(23), ...
        "stft_overlap",         file_lines(25), ...
        "filtering",            file_lines(28), ...
        "filter_order",         file_lines(30), ...
        "approximation_method", file_lines(32), ...
        "filter_type",          file_lines(34), ...
        "cut_off_frequency",    file_lines(36), ...
        "x_lim_time",           file_lines(40), ...
        "y_lim_amplitude",      file_lines(42), ...
        "x_axis_type",          file_lines(45), ...
        "y_axis_type",          file_lines(47), ...
        "x_lim_frequency",      file_lines(49), ...
        "y_lim_au",             file_lines(51));

    structure.wav_fs              = str2num(structure.wav_fs);
    structure.fs                  = str2num(structure.fs);
    structure.signal_duration_s   = str2num(structure.signal_duration_s);
    structure.periodicity_s       = str2num(structure.periodicity_s);
    structure.frequencies         = str2num(structure.frequencies);
    structure.spectral_resolution = str2num(structure.spectral_resolution);
    structure.stft_overlap        = str2num(structure.stft_overlap);
    structure.filter_order        = str2num(structure.filter_order);
    structure.cut_off_frequency   = str2num(structure.cut_off_frequency);
    structure.x_lim_time          = str2num(structure.x_lim_time);
    structure.y_lim_amplitude     = str2num(structure.y_lim_amplitude);
    structure.y_lim_au            = str2num(structure.y_lim_au);

    specs = structure;
end